inp_file: minitown_map.inp
output_path: output
iterations: 60
network_topology_type: complex
log_level: debug
simulator: epynet

plcs: !include minitown_plcs.yaml
#attacks: !include control_attacks.yaml
#attacks: !include mitm_attacks.yaml
attacks: !include dos_attacks.yaml

initial_tank_data: initial_tank.csv
